# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.IntegerField()),
                ('insert_tm', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderInfo', to='pages.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.IntegerField(default=2)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('last_ip', models.CharField(max_length=20, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='pages.Channel')),
            ],
        ),
    ]
