# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installnum', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('charge', models.IntegerField(default=0)),
                ('update_tm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
